# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # rend les classes dans src/disponibles pour être utilisées comme services
  # cela crée un service par classe dont l'identifiant est le nom complet de la classe
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
# ajouter plus de définitions de service lorsqu'une configuration explicite est nécessaire
# veuillez noter que les dernières définitions *remplacent* toujours les précédentes
