version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    env_file:
      - .env
    ports:
      - ${SQL_LOCALHOST_PORT}:${SQL_DOCKER_PORT}
###< doctrine/doctrine-bundle ###


###> symfony/mailer ###
  mailer:
    container_name: MAILPIT_${NAME}
    image: axllent/mailpit
    ports:
      - ${MAILER_LOCALHOST_SMTP_PORT}:${MAILER_DOCKER_SMTP_PORT}
      - ${MAILER_LOCALHOST_HTML_PORT}:${MAILER_DOCKER_HTML_PORT}
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

