-- INSERT INTO
--     `tpa_roles` (`role_code`, `role_name`)
-- VALUES
--     ('ROLE_WEBMASTER', 'webmaster'),
--     ('ROLE_ADMIN', 'admin'),
--     ('ROLE_MOD', 'modérateur'),
--     ('ROLE_USER', 'utilisateur');