services:
  php:
    container_name: backend_${NAME}
    image: backend_${NAME}:${BACKEND_VERSION}
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - database
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

## Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
##> symfony/mercure-bundle ###
##< symfony/mercure-bundle ###

 
  adminer:
    platform: linux/x86_64
    container_name: adminer_${NAME}
    image: adminer:latest
    restart: unless-stopped
    ports:
      - ${ADMINER_LOCAL_PORT}:${ADMINER_DOCKER_PORT}
    env_file:
      - .env
    depends_on:
      - database


###> doctrine/doctrine-bundle ###
  database:
    platform: linux/x86_64
    container_name: mariadb_${NAME}_${MARIADB_VERSION}
    image: mariadb:${MARIADB_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../${PGDATA}/sql:/docker-entrypoint-initdb.d/
      - ../${PGDATA}/${DATABASE_NAME}:/var/lib/mysql
    ports:
      - ${SQL_LOCAL_PORT}:${SQL_DOCKER_PORT}
###< doctrine/doctrine-bundle ###

volumes:
  caddy_data:
  caddy_config:
  tranquillo_sql:
  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
