name: Assign Ticket Number
on:
  pull_request:
    types: [opened]

jobs:
  assign-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Ticket Number
        id: assign
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Convertir le numéro de pull request en entier
            const prNumber = parseInt('${{ github.event.pull_request.number }}');

            // Effectuer la requête GraphQL avec le numéro de pull request correct
            const response = await github.graphql(`
              query {
                repository(owner: "${{ github.repository_owner }}", name: "tranquillo") {
                  pullRequest(number: ${prNumber}) {
                    title
                    body
                  }
                }
              }
            `);

            // Extraire le pull request de la réponse
            const pr = response.repository.pullRequest;

            // Appeler la fonction extractTicketNumber avec le titre du pull request
            const ticketNumber = extractTicketNumber(pr.title);

            // Vérifier si un numéro de ticket a été trouvé
            if (ticketNumber) {
              console.log(`Ticket number found: ${ticketNumber}`);
              // Code pour attribuer le numéro de ticket au PR
            } else {
              console.log('No ticket number found in PR title');
            }

            // Fonction pour extraire le numéro de ticket du titre
            function extractTicketNumber(title) {
              // Définir le motif à rechercher
              const pattern = /ticket\s+(\d+)/i; // Le 'i' signifie que la recherche est insensible à la casse

              // Rechercher le motif dans le titre
              const match = title.match(pattern);

              // Si un match est trouvé, retourner le numéro de ticket
              if (match && match[1]) {
                return match[1];
              } else {
                const pattern = /ticket_+(\d+)/i; // Le 'i' signifie que la recherche est insensible à la casse
                // Rechercher le motif dans le titre
                const match = title.match(pattern);

                // Si un match est trouvé, retourner le numéro de ticket
                if (match && match[1]) {
                  return match[1];
                } else {
                  // Si aucun match n'est trouvé, retourner null
                  return null;
                }
              }
            }
